Add keybinds modmenu, make camera move faster
BasedJellyfish11/HollowKnight.ScreenshotMachine pull request #1
Opened 2022-07-02 04:57 UTC by ygsbzr

2022-07-02 09:05 UTC, BasedJellyfish11 commented
I don't actually maintain this anymore so I'll leave the choice up to @fifty-six, but increasing the camera movement speed this much will reduce precision which is the true goal of the project, so it's not something I agree with. If you want it to move faster, you can double tap the key to run the coroutine twice at the same time.

2022-07-02 11:53 UTC, fifty-six requested changes

2022-07-02 11:53 UTC, fifty-six commented on ScreenshotMachine/CameraHandler.cs
> +                yield return new WaitForSeconds(0.005f);
I'd prefer this stay mostly unchanged, if you want to add speed something like ```cs
yield return new WaitForSeconds(Input.GetKey(Shift) ? 0.005f : 0.1)
```
would be preferable as the precision is very much wanted when taking screenshots.

2022-07-02 11:53 UTC, fifty-six commented on ScreenshotMachine/Settings.cs
> +        public KeyBinds keyBinds = new KeyBinds();
Would prefer this PascalCase'd as it's C#, maybe [SerializedAs("keyBinds")]

2022-07-02 11:53 UTC, fifty-six commented on ScreenshotMachine/ScreenshotMachine.cs
> +        public bool ToggleButtonInsideMenu => false;
Need an empty line between members

2022-07-02 11:54 UTC, fifty-six commented
This looks v nice, thanks. Commented a bit on some minor nits and something regarding the speed stuff.

2022-07-02 11:55 UTC, fifty-six commented on ScreenshotMachine/ModMenu.cs
> +            {
small nit bit the style in this project is no braces for 1 line stuff

2022-07-03 11:01 UTC, fifty-six approved these changes

2022-07-03 11:01 UTC, fifty-six commented
Thank you!

2022-07-03 11:01 UTC, merged